export const backPackItems = [
  { name: "blitzKnuckles", image: "../src/images/item/blitzKnuckles.jpg" },
  { name: "claymore", image: "../images/item/claymore.jpg" },
  { name: "demonEdge", image: "../../../images/item/demonEdge.jpg" },
  { name: "eaglesong", image: "../../../images/item/eaglesong.jpg" },
  { name: "javelin", image: "../../../images/item/javelin.jpg" },
  { name: "mithrilHammer", image: "../../../images/item/mithrilHammer.jpg" },
  { name: "pointBooster", image: "../../../images/item/pointBooster.jpg" },
  { name: "quarterstaff", image: "../../../images/item/quarterstaff.jpg" },
  { name: "sacredRelic", image: "../../../images/item/sacredRelic.jpg" },
  { name: "shadowAmulet", image: "../../../images/item/shadowAmulet.jpg" },
  { name: "talismanOfEvasion", image: "../../../images/item/talismanOfEvasion.jpg" },
  { name: "ultimateOrb", image: "../../../images/item/ultimateOrb.jpg" },
  { name: "beltOfStrength", image: "../../../images/item/beltOfStrength.jpg" },
  { name: "bladeOfalacrity", image: "../../../images/item/bladeOfalacrity.jpg" },
  { name: "bootsOfSpeed", image: "../../../images/item/bootsOfSpeed.jpg" },
  { name: "ghostScepter", image: "../../../images/item/ghostScepter.jpg" },
  { name: "glovesOfHaste", image: "../../../images/item/glovesOfHaste.jpg" },
  { name: "kaya", image: "../../../images/item/kaya.jpg" },
  { name: "morbidMask", image: "../../../images/item/morbidMask.jpg" },
  { name: "ogreAxe", image: "../../../images/item/ogreAxe.jpg" },
  { name: "recipe", image: "../../../images/item/recipe.jpg" },
  { name: "sagesMask", image: "../../../images/item/sagesMask.jpg" },
  { name: "staffOfWizardry", image: "../../../images/item/staffOfWizardry.jpg" },
  { name: "talismanOfEvasion", image: "../../../images/item/talismanOfEvasion.jpg" },
];
