export const backPackItems = [
  { name: "blitzKnuckles", image: "/src/images/item/blitzKnuckles.jpg" },
  { name: "claymore", image: "/src/images/item/claymore.jpg" },
  { name: "demonEdge", image: "/src/images/item/demonEdge.jpg" },
  { name: "eaglesong", image: "/src/images/item/eaglesong.jpg" },
  { name: "javelin", image: "/src/images/item/javelin.jpg" },
  { name: "mithrilHammer", image: "/src/images/item/mithrilHammer.jpg" },
  { name: "pointBooster", image: "/src/images/item/pointBooster.jpg" },
  { name: "quarterstaff", image: "/src/images/item/quarterstaff.jpg" },
  { name: "sacredRelic", image: "/src/images/item/sacredRelic.jpg" },
  { name: "shadowAmulet", image: "/src/images/item/shadowAmulet.jpg" },
  { name: "talismanOfEvasion", image: "/src/images/item/talismanOfEvasion.jpg" },
  { name: "ultimateOrb", image: "/src/images/item/ultimateOrb.jpg" },
  { name: "beltOfStrength", image: "/src/images/item/beltOfStrength.jpg" },
  { name: "bladeOfalacrity", image: "/src/images/item/bladeOfalacrity.jpg" },
  { name: "bootsOfSpeed", image: "/src/images/item/bootsOfSpeed.jpg" },
  { name: "ghostScepter", image: "/src/images/item/ghostScepter.jpg" },
  { name: "glovesOfHaste", image: "/src/images/item/glovesOfHaste.jpg" },
  { name: "kaya", image: "/src/images/item/kaya.jpg" },
  { name: "morbidMask", image: "/src/images/item/morbidMask.jpg" },
  { name: "ogreAxe", image: "/src/images/item/ogreAxe.jpg" },
  { name: "recipe", image: "/src/images/item/recipe.jpg" },
  { name: "sagesMask", image: "/src/images/item/sagesMask.jpg" },
  { name: "staffOfWizardry", image: "/src/images/item/staffOfWizardry.jpg" },
  { name: "talismanOfEvasion", image: "/src/images/item/talismanOfEvasion.jpg" },
];
